[general]
import = ["~/.config/alacritty/theme.toml"]

[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
size = 13

[window]
padding = { x = 14, y = 14 }
opacity = 0.9
blur = true

